//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью wsdl, версия=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_IRegister", Namespace = "http://tempuri.org/")]
public partial class Register : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback IsPaidOperationCompleted;

    private System.Threading.SendOrPostCallback GetProductInfoOperationCompleted;

    /// <remarks/>
    public Register()
    {
        this.Url = "http://register-bsu.cloudapp.net/Register.Service/Register.svc";
    }

    /// <remarks/>
    public event IsPaidCompletedEventHandler IsPaidCompleted;

    /// <remarks/>
    public event GetProductInfoCompletedEventHandler GetProductInfoCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRegister/IsPaid", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void IsPaid([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string clientKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string productKey, out bool IsPaidResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsPaidResultSpecified)
    {
        object[] results = this.Invoke("IsPaid", new object[] {
                    clientKey,
                    productKey});
        IsPaidResult = ((bool)(results[0]));
        IsPaidResultSpecified = ((bool)(results[1]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginIsPaid(string clientKey, string productKey, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("IsPaid", new object[] {
                    clientKey,
                    productKey}, callback, asyncState);
    }

    /// <remarks/>
    public void EndIsPaid(System.IAsyncResult asyncResult, out bool IsPaidResult, out bool IsPaidResultSpecified)
    {
        object[] results = this.EndInvoke(asyncResult);
        IsPaidResult = ((bool)(results[0]));
        IsPaidResultSpecified = ((bool)(results[1]));
    }

    /// <remarks/>
    public void IsPaidAsync(string clientKey, string productKey)
    {
        this.IsPaidAsync(clientKey, productKey, null);
    }

    /// <remarks/>
    public void IsPaidAsync(string clientKey, string productKey, object userState)
    {
        if ((this.IsPaidOperationCompleted == null))
        {
            this.IsPaidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPaidOperationCompleted);
        }
        this.InvokeAsync("IsPaid", new object[] {
                    clientKey,
                    productKey}, this.IsPaidOperationCompleted, userState);
    }

    private void OnIsPaidOperationCompleted(object arg)
    {
        if ((this.IsPaidCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.IsPaidCompleted(this, new IsPaidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRegister/GetProductInfo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public Product GetProductInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string clientKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string productKey)
    {
        object[] results = this.Invoke("GetProductInfo", new object[] {
                    clientKey,
                    productKey});
        return ((Product)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetProductInfo(string clientKey, string productKey, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetProductInfo", new object[] {
                    clientKey,
                    productKey}, callback, asyncState);
    }

    /// <remarks/>
    public Product EndGetProductInfo(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((Product)(results[0]));
    }

    /// <remarks/>
    public void GetProductInfoAsync(string clientKey, string productKey)
    {
        this.GetProductInfoAsync(clientKey, productKey, null);
    }

    /// <remarks/>
    public void GetProductInfoAsync(string clientKey, string productKey, object userState)
    {
        if ((this.GetProductInfoOperationCompleted == null))
        {
            this.GetProductInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductInfoOperationCompleted);
        }
        this.InvokeAsync("GetProductInfo", new object[] {
                    clientKey,
                    productKey}, this.GetProductInfoOperationCompleted, userState);
    }

    private void OnGetProductInfoOperationCompleted(object arg)
    {
        if ((this.GetProductInfoCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProductInfoCompleted(this, new GetProductInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Register.Data.Models")]
public partial class Product
{

    private int idField;

    private bool idFieldSpecified;

    private bool isPaidField;

    private bool isPaidFieldSpecified;

    private string nameField;

    private Payment[] paymentsField;

    private string tokenField;

    /// <remarks/>
    public int Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }

    /// <remarks/>
    public bool IsPaid
    {
        get
        {
            return this.isPaidField;
        }
        set
        {
            this.isPaidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsPaidSpecified
    {
        get
        {
            return this.isPaidFieldSpecified;
        }
        set
        {
            this.isPaidFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public Payment[] Payments
    {
        get
        {
            return this.paymentsField;
        }
        set
        {
            this.paymentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Token
    {
        get
        {
            return this.tokenField;
        }
        set
        {
            this.tokenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Register.Data.Models")]
public partial class Payment
{

    private Client clientField;

    private int clientIdField;

    private bool clientIdFieldSpecified;

    private int idField;

    private bool idFieldSpecified;

    private Product productField;

    private int productIdField;

    private bool productIdFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public Client Client
    {
        get
        {
            return this.clientField;
        }
        set
        {
            this.clientField = value;
        }
    }

    /// <remarks/>
    public int ClientId
    {
        get
        {
            return this.clientIdField;
        }
        set
        {
            this.clientIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClientIdSpecified
    {
        get
        {
            return this.clientIdFieldSpecified;
        }
        set
        {
            this.clientIdFieldSpecified = value;
        }
    }

    /// <remarks/>
    public int Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public Product Product
    {
        get
        {
            return this.productField;
        }
        set
        {
            this.productField = value;
        }
    }

    /// <remarks/>
    public int ProductId
    {
        get
        {
            return this.productIdField;
        }
        set
        {
            this.productIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProductIdSpecified
    {
        get
        {
            return this.productIdFieldSpecified;
        }
        set
        {
            this.productIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Register.Data.Models")]
public partial class Client
{

    private int idField;

    private bool idFieldSpecified;

    private string loginField;

    private string nameField;

    private string passwordField;

    private Payment[] paymentsField;

    private string uniqueIdField;

    /// <remarks/>
    public int Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Login
    {
        get
        {
            return this.loginField;
        }
        set
        {
            this.loginField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public Payment[] Payments
    {
        get
        {
            return this.paymentsField;
        }
        set
        {
            this.paymentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string UniqueId
    {
        get
        {
            return this.uniqueIdField;
        }
        set
        {
            this.uniqueIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void IsPaidCompletedEventHandler(object sender, IsPaidCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class IsPaidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal IsPaidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool IsPaidResult
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }

    /// <remarks/>
    public bool IsPaidResultSpecified
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetProductInfoCompletedEventHandler(object sender, GetProductInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProductInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetProductInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public Product Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((Product)(this.results[0]));
        }
    }
}
